fix: open only PDFs in new tabs
canonical/greenhouse-browser-scripts pull request #54
Opened 2023-10-13 13:17 UTC by tmerten

This looks at the file extension before converting links to be opened in a tab. This way `.docx`s or `.tar.gz`s are still being downloaded. 

Tested on Firefox and Chromium.

Checking the actual mime type might be a bit overkill but could be another (more robust) solution.

2023-10-13 19:27 UTC, anthonydillon commented
That's a rather large lock file change. Do you know what caused it?

2023-10-13 20:37 UTC, anthonydillon requested changes

2023-10-13 20:37 UTC, anthonydillon commented on written-interview-in-new-tab.user.js
> +// ];
Can you remove the commented out code here, please?

2023-10-16 11:04 UTC, tmerten commented
> That's a rather large lock file change. Do you know what caused it?

This was due to a fresh npm install. It should be withing the boundaries of the versions defined in `package.json`.

2023-10-16 11:58 UTC, tmerten commented on written-interview-in-new-tab.user.js
> +// ];
How did these sneak in? Should be gone with the latest commit.

2023-10-16 15:53 UTC, tmerten commented
Hey @anthonydillon . Thanks for the comments. I updated the PR. I'm also happy to revert the `.lock` file; the updates are not needed, just thought it's some maintenance :).

2023-10-17 07:11 UTC, anthonydillon commented
LGTM thanks 👍

2023-10-17 16:11 UTC, tmerten commented
> @tmerten do you want to bump the version of the script in the head of the document so this change is rolled out?

ah. this is how it works. bumped to `1.0.1`

2023-10-26 07:57 UTC, anthonydillon approved these changes
LGTM :+1:

2023-10-26 07:57 UTC, merged